# Use the official Golang image to create a build artifact.
# This is a multi-stage build, so we'll use a temporary image for building.
FROM golang:1.24-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# We want to populate the module cache based on the go.mod file.
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

# Install swag CLI
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Generate swagger docs
RUN /go/bin/swag init

# Build the Go app
# -ldflags="-s -w" is used to make the binary smaller
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o sentinel-backend .

# Use a minimal image to run the application.
FROM alpine:latest

# Add ca-certificates to make SSL calls
RUN apk --no-cache add ca-certificates

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the pre-built binary file from the previous stage
COPY --from=builder /app/sentinel-backend .
COPY --from=builder /app/docs ./docs
COPY GeoLite2-Country.mmdb .
COPY static ./static

# This port will be exposed to the outside world
EXPOSE 6060

# Command to run the executable
CMD ["./sentinel-backend"]